### ISSUE TITLE
Gitea supported ?

### ISSUE THREAD

**Issue by accforgithubtest** [pik4li/ReDeploy#1]
Hello, this looks like a neat project, thank you for creating git.

Are self hosted gitea instances supported ? 
I see only github mentioned in the readme, so wondering if I can use a self hosted gitea instance as well ?

**Comment by pik4li** [comment]
Yes, you can clone every repository, also your own. Ive created it on my private gitea instance as well, and ported it to github, becouse there it gets more attention.

But yes, you can clone from whatever git provider you prefer <3
