### ISSUE TITLE
Automate the hugo theme installation ?

### ISSUE THREAD

**Issue by accforgithubtest** [pik4li/ReDeploy#2]
Is it possible to automate the hugo theme installation ?

I am not yet sure if this is a new feature request, or can be done already somehow.
When using the docker container, can the themes be downloaded to a mounted volume, and applied to few .md files in another mounted folder?

Would highly appreciate it if you can include an example to get a full site working with a specific theme automatically downloaded to a docker volume, and create the site using markdown files in another folder.

**Comment by pik4li** [comment]
This feature is not what this piece of software tries to be.

Its designed for hugo or static websites in general, which need to be "always on" kind of like github pages, or cloudflare pages. With a reverseproxy in the front, you have a website which auto updates, when you push to the main branch, or any branch you prefer.

You have to develop your website by yourself, and every theme has different paths for the files to live, so this could be pretty tricky and is not planned at any time.
